export const orderListStyles = {
  container: {
    display: "flex",
    flexDirection: "column" as const,
    width: "100%",
    height: "100%",
    padding: "24px",
    gap: "24px",
    backgroundColor: "var(--primary)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "24px",
    width: "100%",
  },
  headerLeft: {
    display: "flex",
    flexDirection: "row" as const,
    alignItems: "center",
    gap: "16px",
    flexWrap: "nowrap" as const,
  },
  title: {
    margin: 0,
    fontSize: "24px",
    fontWeight: 600,
    color: "var(--section-title)",
    whiteSpace: "nowrap" as const,
  },
  actionButtons: {
    display: "flex",
    gap: "8px",
  },
  iconButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "40px",
    height: "40px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "var(--section-background)",
    color: "var(--icon-fill)",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  searchContainer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "8px 16px",
    borderRadius: "8px",
    backgroundColor: "var(--section-background)",
    border: "1px solid var(--light-highlight)",
    minWidth: "200px",
  },
  searchIcon: {
    color: "var(--icon-fill)",
    flexShrink: 0,
  },
  searchInput: {
    border: "none",
    outline: "none",
    backgroundColor: "transparent",
    color: "var(--section-title)",
    fontSize: "14px",
    width: "100%",
  },
  tableWrapper: {
    width: "100%",
    overflowX: "auto" as const,
    flex: 1,
    backgroundColor: "var(--section-background)",
    borderRadius: "8px",
    overflow: "hidden" as const,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
  },
  tableHeader: {
    backgroundColor: "var(--section-background)",
  },
  headerCell: {
    padding: "24px 16px",
    textAlign: "left" as const,
    color: "var(--section-title)",
    fontSize: "12px",
    fontWeight: 600,
    borderBottom: "1px solid var(--light-highlight)",
    verticalAlign: "middle" as const,
  },
  headerText: {
    color: "var(--section-title)",
  },
  checkbox: {
    width: "16px",
    height: "16px",
    cursor: "pointer",
    accentColor: "var(--custom-color)",
  },
  tableBody: {
    backgroundColor: "var(--section-background)",
  },
  tableRow: {
    borderBottom: "1px solid var(--light-highlight)",
    transition: "background-color 0.2s",
  },
  tableRowHover: {
    backgroundColor: "var(--order-row-hover)",
  },
  tableCell: {
    padding: "12px 8px",
    color: "var(--section-title)",
    fontSize: "14px",
    fontWeight: 400,
    verticalAlign: "middle" as const,
  },
  orderId: {
    color: "var(--section-title)",
    fontWeight: 500,
  },
  userCell: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  avatar: {
    width: "24px",
    height: "24px",
    borderRadius: "50%",
    objectFit: "cover" as const,
  },
  userName: {
    color: "var(--section-title)",
    fontWeight: 500,
  },
  projectText: {
    color: "var(--section-title)",
  },
  addressCell: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  addressText: {
    color: "var(--section-title)",
  },
  documentIcon: {
    color: "var(--icon-fill)",
    flexShrink: 0,
  },
  dateCell: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  dateIcon: {
    color: "var(--icon-fill)",
    flexShrink: 0,
  },
  dateText: {
    color: "var(--section-title)",
  },
  statusCell: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  statusDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    flexShrink: 0,
  },
  statusText: {
    color: "var(--section-title)",
    fontWeight: 500,
  },
  moreButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "24px",
    height: "24px",
    borderRadius: "4px",
    border: "none",
    backgroundColor: "transparent",
    color: "var(--icon-fill)",
    cursor: "pointer",
    marginLeft: "auto",
  },
  pagination: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "8px",
    paddingTop: "16px",
  },
  paginationButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "var(--section-background)",
    color: "var(--icon-fill)",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  paginationButtonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  paginationNumber: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "32px",
    height: "32px",
    padding: "0 8px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "transparent",
    color: "var(--section-title)",
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  paginationNumberActive: {
    backgroundColor: "var(--order-pagination-active)",
    color: "var(--order-pagination-active-text)",
  },
};
